# -*- coding: utf-8 -*-
"""[2021/02/03] project - yolo - facial identification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZsccZzJpriQXb4x_oxhcZLjaD0m7QvSn
"""

!git clone https://github.com/thtrieu/darkflow

cd darkflow

ls

mkdir images

mkdir annotations

mkdir bin

!sed -i 's/OPENCV=0/OPENCV=1/' Makefile
!sed -i 's/GPU=0/GPU=1/' Makefile
!sed -i 's/CUDNN=0/CUDNN=1/' Makefile

import tensorflow as tf
device_name = tf.test.gpu_device_name()
print(device_name)

!make

!python treino.py